name = "db-mw"
# routes = [{ pattern = "*db.mw/*", zone_name = "db.mw" },{ pattern = "*/*", zone_name = "db.mw" }]
main = "./dist/index.mjs"
usage_model = "unbound"
compatibility_date = "2023-01-01"
logpush = true

services = [
  { binding = "CTX", service = "ctx-do", environment = "production" }
]

workers_dev = false

[build]
command = "npm run build"
 
[build.upload]
format = "modules"

[miniflare]
kv_persist = "./data/"

[miniflare.mounts]
ctx-do = "../ctx.do"