name = "db-mw"
route = { pattern = "*/*", zone_name = "db.mw" }
main = "worker.js"
usage_model = "unbound"
compatibility_date = "2023-01-01"
logpush = true

services = [
  { binding = "CTX", service = "ctx-do", environment = "production" }
]
